url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Environmental Modeling & Computational Mass Spectrometry (EMCMS)" # the name of your site, e.g. ACME Corp.
description: "This is the official website of EMCMS group led by Dr. Saer Samanipour"
