menu:
- {name: 'Projects', url: '/projects'}
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Advanced Chemometrics and Statistics', url: 'ACS'}


social:
- {icon: 'github', link: 'https://github.com/EMCMS'}
- {icon: 'bitbucket', link: 'https://bitbucket.org/SSamanipour/'}
- {icon: 'twitter', link: 'https://twitter.com/ssamanipour'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=q91SSooAAAAJ&hl=en'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0001-8270-6979'}
- {icon: 'linkedin', link: 'https://nl.linkedin.com/in/saer-samanipour-49806847'}

contacts:
- {name: 'Dr. Saer Samanipour', title: 'Assist. Prof.', department: 'HIMS', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 's.samanipour@uva.nl'}
