menu:
- {name: 'Projects', url: '/projects'}
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}

people:
- {name: 'Dr. Saer Samanipour', title: 'Assist. Prof.', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 's.samanipour@uva.nl', image: 'assets/img/66.jpg', url: 'primary-investigator'}
- {name: 'Denice van Herwerden', title: 'PhD Candidate', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'd.vanherwerden@uva.nl', image: 'assets/img/Denice.jpg', url: 'DvH'}
- {name: 'Viktoriia Turkina', title: 'PhD Candidate', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'v.turkina@uva.nl', image: 'assets/img/Vika.png', url: 'Vika'}
- {name: 'Jiani Hu', title: 'MSc Student', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'jiani.hu@student.uva.nl', image: 'assets/img/Jiani.png', url: 'JHU'}
- {name: 'Etienne Kant', title: 'MSc Student', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'etienne.kant@student.uva.nl', image: 'assets/img/EtienneK.jpg', url: 'EtienneK'}
- {name: 'Lisa Vuong', title: 'MSc Student', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'lisa.vuong@student.uva.nl', image: 'assets/img/LisaV.png', url: 'LisaV'}
- {name: 'Alex Nikolopoulos', title: 'MSc Student', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'alex.nikolopoulos@student.uva.nl', image: 'assets/img/AN_small pic.jpg', url: 'AlexN'}
- {name: 'Sanne Boot', title: 'MSc Student', department: 'Vant Hoff Institute for Molecular Science (HIMS)', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 'sanne.boot@student.uva.nl', image: 'assets/img/SanneB.jpg', url: 'SanneB'}

courses:
- {name: 'Advanced Chemometrics and Statistics', url: 'ACS'}


social:
- {icon: 'github', link: 'https://github.com/EMCMS'}
- {icon: 'bitbucket', link: 'https://bitbucket.org/SSamanipour/workspace/repositories'}
- {icon: 'twitter', link: 'https://twitter.com/ssamanipour'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=q91SSooAAAAJ&hl=en'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0001-8270-6979'}
- {icon: 'linkedin', link: 'https://nl.linkedin.com/in/saer-samanipour-49806847'}

contacts:
- {name: 'Dr. Saer Samanipour', title: 'Assist. Prof.', department: 'HIMS', institution: 'University of Amsterdam (UvA)', institution_address: 'Science Park 904, Amsterdam, the Netherlands', email: 's.samanipour@uva.nl'}

news:
- {title: 'New Pre-Print is out', date: '22-06-2022',image: 'assets/img/66.jpg', url: 'Des2tox'}
- {title: 'RTIs of unknown compounds predicted', date: '19-05-2022',image: 'assets/img/66.jpg', url: 'Des2tox'}

